/*

Danny Pham
CSC 134
HW2 - Section 3: CREATE TABLES AND CONSTRAINTS

*/

/* TABLE DATA */
CREATE TABLE TEACHER
(
  TID CHAR(4) NOT NULL,
  Office VARCHAR(10) NOT NULL,
  FirstName VARCHAR(10) NOT NULL,
  LastName VARCHAR(10) NOT NULL,
  PRIMARY KEY (TID)
);

CREATE TABLE STUDENT
(
  SID CHAR(4) NOT NULL,
  FN VARCHAR(10) NOT NULL,
  LN VARCHAR(10) NOT NULL,
  Address VARCHAR(30),
  Gender CHAR,
  PRIMARY KEY (SID)
);

CREATE TABLE PARENT_MEETING
(
  MID CHAR(4) NOT NULL,
  Date DATE,
  Time VARCHAR(6),
  Location VARCHAR(10),
  TeacherID CHAR(4) NOT NULL,
  Hours DECIMAL(5,1),
  SID CHAR(4) NOT NULL,
  Parent_Name VARCHAR(10),
  PRIMARY KEY (MID)
);

CREATE TABLE PARENTS
(
  SID CHAR(4) NOT NULL,
  Name VARCHAR(10) NOT NULL,
  Relationship VARCHAR(10) NOT NULL,
  PRIMARY KEY (SID, Name)
);

CREATE TABLE SUBJECT
(
  TID CHAR(4) NOT NULL,
  Subject VARCHAR(10) NOT NULL,
  PRIMARY KEY (TID, Subject)
);

CREATE TABLE TEACH
(
  TID CHAR(4) NOT NULL,
  SID CHAR(4) NOT NULL,
  times INT NOT NULL,
  PRIMARY KEY (TID, SID)
);


/* FOREIGN KEY CONSTRAINTS */
ALTER TABLE PARENT_MEETING ADD CONSTRAINT Fk_Parents FOREIGN KEY (SID, Parent_Name) REFERENCES PARENTS(SID, Name);

ALTER TABLE PARENT_MEETING ADD CONSTRAINT Fk_TeachID FOREIGN KEY (TeacherID) REFERENCES TEACHER(TID);

ALTER TABLE PARENTS ADD CONSTRAINT Fk_Student FOREIGN KEY (SID) REFERENCES STUDENT(SID);

ALTER TABLE SUBJECT ADD CONSTRAINT Fk_Subject FOREIGN KEY (TID) REFERENCES TEACHER(TID);

ALTER TABLE TEACH ADD CONSTRAINT Fk_Teach FOREIGN KEY (TID) REFERENCES TEACHER(TID);

ALTER TABLE TEACH ADD CONSTRAINT Fk_Teach2 FOREIGN KEY (SID) REFERENCES STUDENT(SID);


/* DESCRIBE TABLE */
DESC TEACHER;
DESC STUDENT;
DESC PARENT_MEETING;
DESC PARENTS;
DESC SUBJECT;
DESC TEACH;
